trigger:
- main

pool:
  name: 'agentpool'

variables:
  SONAR_PROJECT_KEY: 'python-app'
  SONAR_PROJECT_NAME: 'Python App'

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'new_sonarqube'  # Replace with your service connection name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONAR_PROJECT_KEY)'
    cliProjectName: '$(SONAR_PROJECT_NAME)'
    extraProperties: |
      sonar.sources=.
      sonar.language=py
      sonar.python.version=3
      sonar.exclusions=**/__pycache__/**,**/*.pyc
      sonar.host.url=http://192.168.0.104:9000
      sonar.login=$(admin)

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Run your Python tests here (e.g., pytest)"
    # pytest > result.log || true
  displayName: 'Test Application'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
